### ISSUE TITLE
Where do you host the server?

### ISSUE THREAD

**Issue by sugarmaster** [henriquelalves/Godot-Bomber-matchmaking-server#1]
Hi  Henrique,

First I wanted to say thank you because the git is tiny but well documented.

I already went through compiling godot with your pr and all that.

What I need to know now is: Where did you host the node server?
I've been trying Heroku but cant seem to make it work.

In localhost (ubuntu 16) works just fine.

**Comment by henriquelalves** [comment]
Hi! Sorry for taking so long to answer!

I was actually hosting on an Azure VM; I had to set up the port connections to make it work correctly, but it looked fine (and node applications are quite simple to install on VM's). If you are a college student, you can apply for a "test-drive" here: https://azure.microsoft.com/en-us/free/students/

You can use your own PC to test the server too, but then you would need to set-up port-forwarding just for it.

Also, recently they made pull-requested in Godot3 master branch the fix to make hole-punching work, so maybe you should also test that! As soon as I can I will update this repository with it.
